import type { Metadata } from 'next'
import { CartCounter } from '@/shoping-cart/components/CartCounter'

export const metadata: Metadata = {
  title: 'Shoping Cart',
  description: 'Generated by create next app'
}

export default function CounterPage() {
  return (
    <div className=" flex flex-col items-center justify-center w-full h-full">
      <span>Productos en el carrito</span>
      <CartCounter value={10} />
    </div >
  )
}
